### ISSUE TITLE
Sometimes the spellchecker flags correctly spelt words if one adds a full-stop to them

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [openboard-team/openboard#613] opened 2022-05-18 00:31 UTC
**Describe the bug**
When using the OpenBoard spellchecker, typing `<properly spelt word>.` - i.e., a properly spelt word that is followed by a full-sop - underlines `<properly spelt word>.`, as if `properly-spelt-word` were misspelt. Or is it only  `<properly spelt word>` - without the full-stop - that gets underlined (but only when one has added a full-stop)? I do not know, for the bug seems intermittent: once I switched to the Google spellchecker, the problem disappeared, and the problem did not recur even after I switched back to your dictionary. Switching back to Google and then back again to your dictionary did not recreate the problem. But, ah: now the problem has returned.

**To Reproduce**
_Sometimes_ (see above) the following suffices to yield the problem.

1. Set spellcheck to Openboard.
2. In an SMS client - I use Textra - type `<properly spelt word>.` (manually typing the full-stop, i.e., without using the double-tap-spacebar option).
3. See that a spelling mistake is - wrongly - flagged.

**Expected behavior**
A correctly spelt word should not get flagged - should not get tagged as a misspelling merely because one appends a full-stop.

**Screenshots**

![image](https://user-images.githubusercontent.com/47056543/168933188-1aaa0c05-fca6-43cf-bee2-ab905574e284.png)

**Smartphone (please complete the following information):**
 - Device: Asus 'ZenFone' 8
 - OS: Android 12

**Additional context**

Openboard version: 1.4.4 (I think)

Thank you for your software!

**Comment by jnnkB** [comment] 2022-05-26 09:07
Duplicate of #520. Maybe you could add your observations there?

**Closed by jnnkB** 2022-05-26 09:07 UTC
Labels: bug
