### ISSUE TITLE
Text Correction aka Auto Correct issues for email address

### ISSUE THREAD

**Issue by AntaeusBastiat** [openboard-team/openboard#589] opened 2022-04-07 01:57 UTC
Anytime I type an email address such as "[email@address.com](mailto:email@address.com)", the text correction function will correct it as "email address com". I have tried adding every variation of "@address.com" to the personal dictionary, with no luck. Unless you add the exact email address to the personal dictionary, then it will auto correct it. Is there a setting I am missing or something I am doing incorrectly, because this seems kind of strange.

**Comment by jnnkB** [comment] 2022-04-07 08:18
Duplicate of #425

**Closed by jnnkB** 2022-04-07 08:18 UTC
Labels: bug
