### ISSUE TITLE
Allow glide typing

### ISSUE THREAD

**Issue by harmony5** [openboard-team/openboard#505] opened 2022-01-27 08:37 UTC
**Problem**
Non-glide can feel slow and also not very comfortable when using the keyboard with just one hand.

**Solution**
Glide typing can enhance the user experience, typing speed and accessibility by allowing to type with just one hand gliding over the letters to form the desired words.

**Comment by jnnkB** [comment] 2022-01-28 21:22
Duplicate of #3

**Closed by jnnkB** 2022-01-28 21:22 UTC
Labels: enhancement
