### ISSUE TITLE
Show "ß" first in pop-up after long-press "s" and support uppercase ẞ (German Keyboard)

### ISSUE THREAD

**Issue by Litom** [openboard-team/openboard#684] opened 2022-08-20 13:55 UTC
On the German keyboard, the primary selection after a long press of the "s" character is "#", which is unusual for a German keyboard layout. 

The character "ß" is present in many German words and is used more frequently. Furthermore if capitalisation is activated, there is no possibility to select a "ẞ" in capital letters.

**Solution:**
Make "ß" the primary selection after a long press of "s" and "ẞ" the primary selection after a long press of "S".

**Current Situation:**
![example](https://user-images.githubusercontent.com/18378982/185748760-5ed65276-2a5e-4fe2-b2f3-ebd359de7d82.png)

**How other German keyboards have it:**
![example2](https://user-images.githubusercontent.com/18378982/185748881-e62b446a-afa4-44af-b04e-8948c004b081.jpeg)

---

**Uppercase Situation:**
![example3](https://user-images.githubusercontent.com/18378982/185748985-be9ba181-36c7-4de6-95cf-de8f62b8dd96.jpeg)

**Comment by Helium314** [comment] 2022-08-21 05:48
looks like a duplicate of #657

**Closed** 2022-08-21 20:03 UTC
