### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by mfdood** [openboard-team/openboard#536] opened 2022-02-13 16:31 UTC
Missing emojis
Even though i m on android 11, some emojis are missing such as 😮‍💨 and 😶‍🌫️
 - Device: Poco X3 NFC
 - OS: Lineageos 18.1 for microg

**Comment by jnnkB** [comment] 2022-02-14 08:36
duplicate of #462

**Closed by jnnkB** 2022-02-14 08:36 UTC
Labels: bug
