### ISSUE TITLE
Ability to delete suggested words provided from system dictionary so they aren't suggested again

### ISSUE THREAD

**Issue by Candlemass** [openboard-team/openboard#531] opened 2022-02-08 10:43 UTC
Hello,

I like word suggestions as it often makes typing on a phone quicker. However I have personalized/learned words disabled for privacy reasons and the suggestions only come from the system dictionary. Every other keyboard that I have tried setup in the same way provides the option to delete word suggestions so that they do not appear again by long pressing them.

Why is this not an option in OpenBoard?

Thank you.

**Comment by jnnkB** [comment] 2022-02-14 08:38
duplicate of #313

**Closed by jnnkB** 2022-02-14 08:38 UTC
Labels: enhancement
