### ISSUE TITLE
[Feature Request] Turkish-Q layout support

### ISSUE THREAD

**Issue by ondern** [openboard-team/openboard#670] opened 2022-08-14 15:29 UTC

**Comment by ondern** [comment] 2022-08-14 15:30
https://github.com/rkkr/simple-keyboard

This app provide Turkish-Q layout support. You can fork the code.

**Comment by ondern** [comment] 2022-08-14 15:32
https://github.com/rkkr/simple-keyboard

This app provide Turkish-Q layout support. You can fork the code.![184511165-6ad08b60-1ace-4f1a-a29b-5aab5076db69.png](https://user-images.githubusercontent.com/109258788/184544158-d742677c-5ab5-4d83-a27b-8a193b09b159.png)![184511163-fced9696-52a3-4f93-b557-28c2f9d438ae.png](https://user-images.githubusercontent.com/109258788/184544162-c166a1f4-d86a-4b7d-b1a8-90046923ede3.png)![184511158-1ccc6579-a509-46f1-aeaf-b8385804472c.png](https://user-images.githubusercontent.com/109258788/184544166-e1741b8a-4613-480d-b6b3-87baff42bab2.png)![184511156-143d9c4f-9e8c-4cb0-a6ae-9605ba31754c.png](https://user-images.githubusercontent.com/109258788/184544167-ab33770b-015a-410a-9a90-0916b87f124b.png)![184511152-40445d6a-f9fe-4b67-81ee-df846218823b.png](https://user-images.githubusercontent.com/109258788/184544170-a4b9996b-dd85-4a05-a34e-eb44956ef7b7.png)![184511151-0bd56570-af83-4fd1-8b78-9a86a81884ac.png](https://user-images.githubusercontent.com/109258788/184544172-eb65ac86-e2dc-4e2a-8407-891925daf80f.png)

**Comment by jnnkB** [comment] 2022-08-16 07:41
I think this is a duplicate of #309. Maybe you could provide your information there?

**Closed by jnnkB** 2022-08-16 07:41 UTC
Labels: enhancement
