### ISSUE TITLE
Cross language suggestions

### ISSUE THREAD

**Issue by yaoberh** [openboard-team/openboard#675] opened 2022-08-16 21:10 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Sometimes one needs to type in two languages when writing in a messaging app or facebook/twitter/etc, and the dictionary suggestions are always only for the currently in use language/keyboard

**Describe alternatives you've considered**
Google input offers this option as cross language typing/dictionaries

**Comment by NoahAndrews** [comment] 2022-08-17 00:25
There's actually a draft pull request for this feature: https://github.com/openboard-team/openboard/pull/586

**Comment by jnnkB** [comment] 2022-12-09 19:50
duplicate of #167 and/or #7

**Closed** 2022-12-09 19:50 UTC
Labels: enhancement
