### ISSUE TITLE
Serbian Cyrillic problem layout

### ISSUE THREAD

**Issue by KurozyOS** [openboard-team/openboard#671] opened 2022-08-14 18:27 UTC
There is one key that does not belong to the Serbian Cyrillic table. Suggestion is to remove the key and it makes more space for backspace.
![IMG_20220814_202645](https://user-images.githubusercontent.com/81830783/184550072-c2b6916e-9eb4-4dca-bd56-ce06b6bc2609.jpg)

**Comment by jnnkB** [comment] 2022-08-16 07:37
duplicate of #299

**Closed by jnnkB** 2022-08-16 07:37 UTC
Labels: layout
