### ISSUE TITLE
Customised input styles "+" button is white on white background

### ISSUE THREAD

**Issue by coolmule0** [openboard-team/openboard#503] opened 2022-01-24 12:32 UTC
**Describe the bug**
OpenBoard Settings -> Appearance and Layouts -> Customised input styles. I noticed that pressing the top right shows a little "+" symbol. However, my theming shows it as a white button on a white background, so invisible without interacting with it. 
The button should be provided and alternate, visible color.

**To Reproduce**
1. Visit OpenBoard Settings -> Appearance and Layouts -> Customised input styles

**Expected behavior**
A visible button to show clearly to add new layouts

**Screenshots**

<img src="https://user-images.githubusercontent.com/13734115/150782919-2baec050-d3b8-49c6-859f-b9a13c71f6fd.png" alt="screenshot" width="300"/>
See top right for expected location

**Smartphone (please complete the following information):**
 - Device:  Sony Xperia XZ2
 - Model: H82116
 - OS: Android 10
 - Installed on both FDroid and GooglePlay

**Comment by jnnkB** [comment] 2022-01-24 19:29
Duplicate of #135

**Closed by jnnkB** 2022-01-24 19:29 UTC
Labels: bug
