### ISSUE TITLE
new themes

### ISSUE THREAD

**Issue by murph2495** [openboard-team/openboard#525] opened 2022-02-05 16:45 UTC
it would be nice if there were new themes to customize the keyboard . Thanks

**Comment by jnnkB** [comment] 2022-02-05 20:10
Do you mean something along the lines of #124 or do you want some specific theme?

**Comment by murph2495** [comment] 2022-02-05 20:47
Yes. custom colors and images. it would be very nice to also see the Android 12 design lines or something you guys have in mind

**Comment by jnnkB** [comment] 2022-07-31 08:05
Duplicate of 124

**Closed by jnnkB** 2022-07-31 08:05 UTC
Labels: enhancement
