### ISSUE TITLE
Feature Request: Text Editing, One-Handed Mode, Floating.

### ISSUE THREAD

**Issue by hiru12** [openboard-team/openboard#229] opened 2020-11-22 17:57 UTC
I think these three features are essential for keyboards. 
![Screenshot_2020_1123_013121](https://user-images.githubusercontent.com/74873448/99911411-315fb200-2d2f-11eb-806c-bf67c1e8f0b4.png)

**Comment by kojid0** [comment] 2020-11-22 18:22
Please divide those 3 requests and explain the requests.

Have you checked existing issues?
One-Hand mode: duplicate of #13.

What do you mean with Text Editing?

**Closed** 2022-03-01 12:23 UTC
