### ISSUE TITLE
A way to disable the clipboard manager feature

### ISSUE THREAD

**Issue by user-2022** [openboard-team/openboard#535] opened 2022-02-12 15:55 UTC
I use a third-party clipboard manager so I'm more comfortable with navigation as in previous OpenBoard versions, when a long swipe on the Enter opens only one option (emoji button). So I think it would be nice to have a settings to turn off the clipboard manager feature. Or even better, a setting to configure which keys open which options on a long swipe, for example «Comma key displays: ☑️ emoji ☑️ settings ☑️ clipboard», and same thing for the Enter key. So it would be possible to enable or disable this options.

**Comment by jnnkB** [comment] 2022-02-14 08:35
This is partly a duplicate of #497

**Closed** 2022-02-18 20:29 UTC
Labels: enhancement
