### ISSUE TITLE
Things to make openboard easier to use with one hand

### ISSUE THREAD

**Issue by Ciliane** [openboard-team/openboard#554] opened 2022-03-01 21:32 UTC
**Is your feature request related to a problem? Please describe.**
So I often my left hand away from the phone when I expect it to be not needed but some menus such as clipboard history selection buttons are far apart from each other on sides and it forces me to reach the "ABC" button with the thumb far across the entire screen, and it's annoying. The same problem with emoji menu.

**Describe the solution you'd like**
Move the buttons in emoji and clipboard menus to one side, probably add a left handed mode to move them to left.

**Comment by jnnkB** [comment] 2022-03-02 10:14
Duplicate of #13. FIxed in https://github.com/openboard-team/openboard/pull/545

**Closed by jnnkB** 2022-03-02 10:14 UTC
Labels: enhancement
