### ISSUE TITLE
Show key hints advanced option

Replace switch on/off with submenu with 3 hints showing options: 1. Show all. 2. Numbers only. 3. Hide all.


### ISSUE THREAD

**Issue by Atrafon** [openboard-team/openboard#673] opened 2022-08-15 20:47 UTC
1. Show all ![Screenshot_20220815_233929_com.github.android.jpg](https://user-images.githubusercontent.com/106192957/184715179-7b37b8f1-6629-4233-9130-a118878d3f42.jpg)
2. Numbers only (as in Simple keyboard)
![Screenshot_20220815_234005_com.github.android.jpg](https://user-images.githubusercontent.com/106192957/184715263-154fd930-5226-475a-b1d8-964056ca59ce.jpg)
3. Hide all ![Screenshot_20220815_233915_com.github.android.jpg](https://user-images.githubusercontent.com/106192957/184715317-a1e304de-a88d-4f79-a949-fa0ce245f643.jpg)

**Comment by NoahAndrews** [comment] 2022-08-16 15:02
Duplicate of #356.

**Closed** 2022-08-17 07:45 UTC
Labels: enhancement
