### ISSUE TITLE
Hand emojis stay

### ISSUE THREAD

**Issue by sanni88** [openboard-team/openboard#476] opened 2021-12-16 22:39 UTC
Hi
You go to emojis. You search for the "perfect" hand symbol. You want to take the brown hand rather than the yellow one and press long on the yellow hand. All colored hands are shown. You choose a brown hand. Brown hand is inserted in the text box but the optional hands will stay and overlap the keyboard. 
Only restart of the phone helps.

**Comment by jnnkB** [comment] 2021-12-17 09:15
Hey, I couldn't reproduce this. Could you send a screenshot and which version of the app on which Android you are using?

**Comment by GithubContributor832** [comment] 2021-12-30 23:42
This is a bug. It happens when you long press a hand symbol then swipe up to get options to stick in view. Normally click that same hand symbol closes the options. However go to ABC on keyboard before closing options out in emoji section they stick in view. Must restart. It must be closed before you exit or it sticks. Going back to close doesn't work.

**Comment by GithubContributor832** [comment] 2021-12-30 23:45
Force stop keyboard then reopen fixes it too.

**Comment by sanni88** [comment] 2022-01-01 15:47
True, force stop works. Its not a solution but its a workaround. thank you. What I also noticed is that the symbol will not be in the favorites (last used emojis). So next time you wanna send a dark skin hand you cannot simply use the one in the favorites and you will have the same issue again..

 
 

Gesendet: Freitag, 31. Dezember 2021 um 00:45 Uhr
Von: "GithubContributor832" ***@***.***>
An: "dslul/openboard" ***@***.***>
Cc: "sanni88" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [dslul/openboard] Hand emojis stay (Issue #476)


 

Force stop keyboard then reopen fixes it too.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sanni88** [comment] 2022-01-01 15:55
i can confirm this. pressing on the same or another standard symbol will help too. but somhow it is strange. after several times pressing the dark hand and then another emoji at one moment the keyboard removes the options (it works as it should be). 

Thank you anyway. i know how to solve it thanks to you both and I dont wanna make more work than necessary to the creator.

thanks again and have a good start in the new year!

 
 

Gesendet: Freitag, 31. Dezember 2021 um 00:43 Uhr
Von: "GithubContributor832" ***@***.***>
An: "dslul/openboard" ***@***.***>
Cc: "sanni88" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [dslul/openboard] Hand emojis stay (Issue #476)


 

This is a bug. It happens when you long press a hand symbol then swipe up to get options to stick in view. Normally click that same hand symbol closes the options. However go to ABC on keyboard before closing options out in emoji section they stick in view. Must restart. It must be closed before you exit or it sticks. Going back to close doesn't work.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MajeurAndroid** [comment] 2022-01-03 14:57
Which version of the keyboard are you using ? Is the emoji scrolling list feature present ?
I almost entirely fixed this bug, it was caused by a touch event triggered from outside of the keyboard window, but it may be still happening in some cases.

**Comment by sanni88** [comment] 2022-01-03 15:42
I use 1.4.3
I think the scrolling feature is present. I can continuously scoll down and will go threw all kind of topics.


Am 3. Januar 2022 15:57:52 MEZ schrieb Majeur ***@***.***>:

**Comment by MajeurAndroid** [comment] 2022-01-03 17:58
Ok, you'll have to try with the next release, I'm pretty sure the fix is in the code.

**Comment by sanni88** [comment] 2022-01-03 22:38
No problem. I will do so!
Thank you for your hard work!

Am 3. Januar 2022 18:58:19 MEZ schrieb Majeur ***@***.***>:

**Comment by sanni88** [comment] 2022-01-18 19:41
Oh thank you for telling me that there is another version available. My /e/ app store shows still the 1.4.3 and fdroid does that too. I tried to install the apk from here but it didn't work. I guess because I installed it originally from the /e/ app store. I could uninstall it from the store and then manually install the apk but I risk to loose my settings so I have to wait until one of the shops offering it

Am 18. Januar 2022 19:09:29 MEZ schrieb Majeur ***@***.***>:
***@***.*** can you reproduce the bug with the 1.4.4 release ?

**Comment by MajeurAndroid** [comment] 2022-01-30 10:48
@sanni88 is the bug still there ?

**Comment by sanni88** [comment] 2022-01-30 19:21
I check from time to time in the mentioned app stores if the 1.4.4 is available but so far it doesn't. Maybe the owner must upload it or something?

Am 30. Januar 2022 11:48:15 MEZ schrieb Majeur ***@***.***>:
***@***.*** is the bug still there ?

**Comment by dslul** [comment] 2022-01-30 19:23
> I check from time to time in the mentioned app stores if the 1.4.4 is available but so far it doesn't. Maybe the owner must upload it or something?

it is already updated on both stores, check again

**Comment by sanni88** [comment] 2022-01-31 06:10
🙏🏽
Does this answer your question?😜😅🙏🏽🙏🏽

Am 30. Januar 2022 20:24:05 MEZ schrieb Daniele Laudani ***@***.***>:

**Closed** 2022-01-31 10:46 UTC
Labels: bug
